[package]
name = "puffersecuresigner"
version = "1.0.0"
authors = ["Jason Vranek <jason@portalcompute.com>"]
build = "build.rs"
edition = "2021"

[build-dependencies]
cc = "1.0"

[dependencies]
libc = "0.2"

# io deps
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde-hex = "0.1.0"

# crypto deps
blst = "0.3.10"
rand = "0.7"
rand_chacha = "0.2"
hex = "0.4.3"
ecies = {version = "0.2.2", default-features = false, features = ["pure"]}
sha3 = "0.10.1"
openssl = "0.10.42"
bytes = "1"

# eth deps
eth2_ssz = "0.4.0"
eth2_ssz_derive = "0.3.0"
eth2_ssz_types = "0.2.1"
tree_hash = "0.4.0"
tree_hash_derive = "0.4.0"

# server deps
tokio = { version = "1", features = ["full"] }
warp = "0.3"

# client deps
reqwest = { version = "0.11", features = ["json"] }

# misc
anyhow = "1.0.65"

[[bin]] # Bin to run the sgx-signer rpc
name = "secure-signer"
path = "src/secure_signer.rs"

[[bin]] # Bin to run the client 
name = "client"
path = "src/client.rs"