[package]
name = "portaldatafeeds"
version = "1.0.0"
authors = ["Jason Vranek <jason@portalcompute.com>"]
build = "build.rs"
edition = "2021"

[build-dependencies]
cc = "1.0"

[dependencies]
libc = "0.2"

# io deps
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

# crypto deps
blst = "0.3.10"
rand = "0.7"
rand_chacha = "0.2"
hex = "0.4.3"
ecies = {version = "0.2.2", default-features = false, features = ["pure"]}
sha3 = "0.10.1"
# base64 = "0.13.0"
openssl = "0.10.42"

# web3 deps
ethabi = { version = "17.1.0", default-features = false }
ethereum-tx-sign = "4.0.0"

# server deps
tokio = { version = "1", features = ["full"] }
warp = "0.3"

# client deps
reqwest = { version = "0.11", features = ["json"] }


# misc
anyhow = "1.0.65"


[[bin]] # Bin to run the worker node
name = "worker"
path = "src/worker.rs"

[[bin]] # Bin to run the leader node
name = "leader"
path = "src/leader.rs"

[[bin]] # Bin to run the sgx-signer rpc
name = "sgx-signer"
path = "src/sgx_signer.rs"