openapi: 3.0.3
info:
  title: 'Puffer Secure-Signer Api'
  description: 'Sign Eth2 Artifacts'
  version: '0.1'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

servers:
  - url: /
  - url: http://localhost:9000/

paths:
  /api/v1/eth2/sign/{identifier}:
    $ref: './signing/paths/sign.yaml'
  /api/v1/eth2/sign/deposit/{identifier}:
    $ref: './signing/paths/deposit.yaml'
  /upcheck:
    $ref: './signing/paths/upcheck.yaml'
  /eth/v1/keygen/bls:
    $ref: './keygen/paths/bls_keygen.yaml'
  /eth/v1/keygen/secp256k1:
    $ref: './keygen/paths/secp256k1_keygen.yaml'
  /eth/v1/keystores:
    $ref: './keymanager/paths/keystores.yaml'

externalDocs:
  description: 'Secure-Signer User Documentation'
  #publicsh this on github pages
  # url: ''
